server:
  # 应用服务 WEB 访问端口
  port: 8080
  servlet:
    context-path: /springboot-jpa

spring:
  application:
    #应用名称
    name: springboot-jpa
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    # 数据库用户名密码：
    username: root
    password: doujiyuan

  #jpa配置
  jpa:
    #jpa操作的数据库类型
    database: mysql
    #操作时在控制台显示sql语句
    show-sql: true
    #ddl语句或者实体类有变化，自动更新表结构
    hibernate.ddl-auto: update




